<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="customerRequest.aspx.cs" Inherits="dvdmanagementsystem.customerRequest" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body style="height: 347px">
    <form id="form1" runat="server">
    <div>
    
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Width="800px" AllowSorting="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" Caption="Request From User" CaptionAlign="Top" CellPadding="4" CellSpacing="2" ForeColor="Black" HorizontalAlign="Center" RowHeaderColumn="moviename" TabIndex="8" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <Columns>
                <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" ReadOnly="True" SortExpression="id" />
                <asp:BoundField DataField="moviename" HeaderText="moviename" SortExpression="moviename" />
                <asp:BoundField DataField="actor" HeaderText="actor" SortExpression="actor" />
                <asp:BoundField DataField="actress" HeaderText="actress" SortExpression="actress" />
                <asp:BoundField DataField="director" HeaderText="director" SortExpression="director" />
                <asp:BoundField DataField="comment" HeaderText="comment" SortExpression="comment" />
                <asp:BoundField DataField="userName" HeaderText="userName" SortExpression="userName" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
            <RowStyle BackColor="White" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DBCS %>" SelectCommand="SELECT * FROM [userRequest]" DeleteCommand ="DELETE FROM [userRequest] where [id]=@id"></asp:SqlDataSource>
    
        <br />
        <asp:Button ID="Button1" runat="server" BackColor="#99CCFF" Font-Bold="True" Font-Italic="True" ForeColor="#000066" Height="41px" OnClick="Button1_Click" Text="Back" Width="88px" />
        <br />
        <br />
    
    </div>
    </form>
</body>
</html>
