<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="showDVD.aspx.cs" Inherits="dvdmanagementsystem.showDVD" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div align="center">
    
        <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Size="Larger" Text="All DVD List"></asp:Label>
    
    </div>

    <div align="center" style="margin-bottom:30px;margin-top:30px;">
    
        <asp:Label ID="Label2" runat="server" Text="Search :"></asp:Label>
        <asp:TextBox ID="whatTofind" runat="server"></asp:TextBox>
        <asp:Label ID="Label3" runat="server" Text="By :"></asp:Label>
        <asp:DropDownList ID="whatTofindBy" runat="server">
            <asp:ListItem>title</asp:ListItem>
            <asp:ListItem>actor</asp:ListItem>
            <asp:ListItem>actress</asp:ListItem>
            <asp:ListItem>director</asp:ListItem>
            <asp:ListItem>year</asp:ListItem>
            <asp:ListItem>category1</asp:ListItem>
            <asp:ListItem>category2</asp:ListItem>
        </asp:DropDownList>
        <asp:Button ID="Button1" runat="server" Text="Go" OnClick="Button1_Click" />
    </div>


    <div align="center">
    
        <asp:GridView ID="GridView1" runat="server" CellPadding="5" ForeColor="#333333" GridLines="None" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1" DataKeyNames="item" CellSpacing="2" AllowPaging="True" PageSize="7">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="title" HeaderText="title" SortExpression="title" />
                <asp:BoundField DataField="actor" HeaderText="actor" SortExpression="actor" />
                <asp:BoundField DataField="actress" HeaderText="actress" SortExpression="actress" />
                <asp:BoundField DataField="director" HeaderText="director" SortExpression="director" />
                <asp:BoundField DataField="year" HeaderText="year" SortExpression="year" />
                <asp:BoundField DataField="category1" HeaderText="category1" SortExpression="category1" />
                <asp:BoundField DataField="category2" HeaderText="category2" SortExpression="category2" />
                <asp:BoundField DataField="item" HeaderText="item" InsertVisible="False" ReadOnly="True" SortExpression="item" />
            </Columns>
            <EditRowStyle BackColor="#7C6F57" />
            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#E3EAEB" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F8FAFA" />
            <SortedAscendingHeaderStyle BackColor="#246B61" />
            <SortedDescendingCellStyle BackColor="#D4DFE1" />
            <SortedDescendingHeaderStyle BackColor="#15524A" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DBCS %>" SelectCommand="SELECT * FROM [movielist]" UpdateCommand="UPDATE [movielist] set [title]=@title,[actor]=@actor,[actress]=@actress,[director]=@director,[year]=@year,[category1]=@category1,[category2]=@category2 where [item]=@item "  DeleteCommand ="DELETE FROM [movielist] where [item]=@item"></asp:SqlDataSource>
        <asp:Button ID="Button2" runat="server" BackColor="#339933" Font-Bold="True" ForeColor="White" Height="45px" OnClick="Button2_Click" Text="Home" Width="122px" />
    <asp:Button ID="signOutButton" runat="server" Text="Sign Out" BackColor="#DD5044" Font-Bold="True" ForeColor="White" Height="47px" OnClick="signOutButton_Click" Width="151px" />
    </div>

    </form>
</body>
</html>
